### ISSUE TITLE
About the  ECE？

### ISSUE THREAD

**Issue by hmyh1202** [Magdoll/ECE#1]
Hi, 
What is the main function of the ECE package？

And can you provide some knowlege and publish for us ?

Thank you !

**Comment by Magdoll** [comment]
Hi @hmyh1202 ,

This is the code used in the paper
Algorithms for locating extremely conserved elements in multiple sequence alignments
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2808710/

I do not intend to publicly support this code base. Use at your own risk.

-Liz
